services:
  content_api_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: content
      POSTGRES_PASSWORD: content
      POSTGRES_DB: content-api-db
    ports:
      - '5432:5432'
    networks:
      - tlp

networks:
  tlp:
    driver: bridge
